# ruff: noqa: E501
"""initial schema

Revision ID: 20260713_0001
Revises:
Create Date: 2026-07-13 21:04:52.292965
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260713_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buildings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(create_constraint=True, name="is_active_bool"),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_buildings_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buildings")),
        sa.UniqueConstraint("name", name=op.f("uq_buildings_name")),
    )
    op.create_table(
        "course_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(create_constraint=True, name="is_active_bool"),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_course_categories_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_course_categories_name")),
    )
    op.create_table(
        "gender_codes",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("label", sa.String(length=40), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_gender_codes")),
        sa.UniqueConstraint("label", name=op.f("uq_gender_codes_label")),
    )
    gender_codes = sa.table(
        "gender_codes",
        sa.column("code", sa.String(length=16)),
        sa.column("label", sa.String(length=40)),
        sa.column("sort_order", sa.Integer()),
    )
    op.bulk_insert(
        gender_codes,
        [
            {"code": "male", "label": "남성", "sort_order": 1},
            {"code": "female", "label": "여성", "sort_order": 2},
            {"code": "unknown", "label": "미상", "sort_order": 3},
        ],
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("namespace", sa.String(length=160), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('processing', 'completed', 'failed')",
            name=op.f("ck_idempotency_records_status_allowed"),
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_idempotency_records_expiry_after_creation")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint(
            "namespace", "key_hash", name=op.f("uq_idempotency_records_namespace_key_hash")
        ),
    )
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.create_index("ix_idempotency_records_expires_at", ["expires_at"], unique=False)

    op.create_table(
        "instructors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(create_constraint=True, name="is_active_bool"),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_instructors_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instructors")),
    )
    op.create_table(
        "location_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "is_course_eligible",
            sa.Boolean(create_constraint=True, name="is_course_eligible_bool"),
            server_default="0",
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(create_constraint=True, name="is_active_bool"),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_location_roles_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_location_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_location_roles_name")),
    )
    op.create_table(
        "operation_locks",
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=80), nullable=False),
        sa.Column("operation", sa.String(length=80), nullable=False),
        sa.Column("owner_token", sa.String(length=64), nullable=False),
        sa.Column(
            "acquired_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "expires_at > acquired_at", name=op.f("ck_operation_locks_expiry_after_acquire")
        ),
        sa.PrimaryKeyConstraint("resource_type", "resource_id", name=op.f("pk_operation_locks")),
    )
    with op.batch_alter_table("operation_locks", schema=None) as batch_op:
        batch_op.create_index("ix_operation_locks_expires_at", ["expires_at"], unique=False)

    op.create_table(
        "organization_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_name", sa.String(length=120), nullable=False),
        sa.Column("logo_relative_path", sa.String(length=260), nullable=True),
        sa.Column("default_max_registrations", sa.Integer(), server_default="4", nullable=False),
        sa.Column(
            "default_access_code_ttl_minutes", sa.Integer(), server_default="480", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "default_access_code_ttl_minutes BETWEEN 1 AND 10080",
            name=op.f("ck_organization_settings_access_code_ttl_range"),
        ),
        sa.CheckConstraint(
            "default_max_registrations >= 0",
            name=op.f("ck_organization_settings_default_limit_nonnegative"),
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_organization_settings_singleton_id")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_organization_settings_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_settings")),
    )
    op.create_table(
        "terms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("registration_opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("registration_closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_registrations_per_member", sa.Integer(), server_default="0", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'open', 'closed', 'finalized')",
            name=op.f("ck_terms_status_allowed"),
        ),
        sa.CheckConstraint(
            "max_registrations_per_member >= 0",
            name=op.f("ck_terms_registration_limit_nonnegative"),
        ),
        sa.CheckConstraint(
            "registration_opens_at IS NULL OR registration_closes_at IS NULL OR registration_opens_at < registration_closes_at",
            name=op.f("ck_terms_registration_range_valid"),
        ),
        sa.CheckConstraint(
            "starts_on IS NULL OR ends_on IS NULL OR starts_on <= ends_on",
            name=op.f("ck_terms_date_range_valid"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_terms_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_terms")),
        sa.UniqueConstraint("name", name=op.f("uq_terms_name")),
    )
    op.create_table(
        "time_slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(create_constraint=True, name="is_active_bool"),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("start_time < end_time", name=op.f("ck_time_slots_time_range_valid")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_time_slots_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_time_slots")),
        sa.UniqueConstraint("name", name=op.f("uq_time_slots_name")),
        sa.UniqueConstraint(
            "start_time", "end_time", name=op.f("uq_time_slots_start_time_end_time")
        ),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("affiliation", sa.String(length=120), nullable=True),
        sa.Column("contact_note", sa.String(length=120), nullable=True),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(create_constraint=True, name="is_active_bool"),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "role IN ('staff', 'temporary_staff', 'viewer')", name=op.f("ck_users_role_allowed")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_users_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("ix_users_role_is_active", ["role", "is_active"], unique=False)

    op.create_table(
        "access_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("code_hash", sa.String(length=255), nullable=False),
        sa.Column("display_code", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hidden_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "expires_at > issued_at", name=op.f("ck_access_codes_expiry_after_issue")
        ),
        sa.CheckConstraint(
            "hidden_at IS NULL OR hidden_at >= issued_at",
            name=op.f("ck_access_codes_hidden_after_issue"),
        ),
        sa.CheckConstraint(
            "revoked_at IS NULL OR revoked_at >= issued_at",
            name=op.f("ck_access_codes_revoked_after_issue"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_access_codes_version_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_access_codes_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_codes")),
        sa.UniqueConstraint("code_hash", name=op.f("uq_access_codes_code_hash")),
        sa.UniqueConstraint("display_code", name=op.f("uq_access_codes_display_code")),
    )
    with op.batch_alter_table("access_codes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_access_codes_lifecycle", ["expires_at", "revoked_at", "hidden_at"], unique=False
        )
        batch_op.create_index("ix_access_codes_user_id", ["user_id"], unique=False)

    op.create_table(
        "building_floors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(create_constraint=True, name="is_active_bool"),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_building_floors_version_positive")),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
            name=op.f("fk_building_floors_building_id_buildings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_building_floors")),
        sa.UniqueConstraint(
            "building_id", "label", name=op.f("uq_building_floors_building_id_label")
        ),
    )
    with op.batch_alter_table("building_floors", schema=None) as batch_op:
        batch_op.create_index("ix_building_floors_building_id", ["building_id"], unique=False)

    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(create_constraint=True, name="is_active_bool"),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_courses_version_positive")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["course_categories.id"],
            name=op.f("fk_courses_category_id_course_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
        sa.UniqueConstraint("category_id", "name", name=op.f("uq_courses_category_id_name")),
    )
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.create_index(
            "ix_courses_category_active", ["category_id", "is_active"], unique=False
        )

    op.create_table(
        "lottery_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("term_id", sa.Integer(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="prepared", nullable=False),
        sa.Column("executed_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('prepared', 'running', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_lottery_runs_status_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["executed_by_user_id"],
            ["users.id"],
            name=op.f("fk_lottery_runs_executed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
            name=op.f("fk_lottery_runs_term_id_terms"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lottery_runs")),
    )
    with op.batch_alter_table("lottery_runs", schema=None) as batch_op:
        batch_op.create_index("ix_lottery_runs_term_status", ["term_id", "status"], unique=False)

    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_no", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("gender_code", sa.String(length=16), server_default="unknown", nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(create_constraint=True, name="is_active_bool"),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_members_version_positive")),
        sa.ForeignKeyConstraint(
            ["gender_code"],
            ["gender_codes.code"],
            name=op.f("fk_members_gender_code_gender_codes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_members")),
        sa.UniqueConstraint("member_no", name=op.f("uq_members_member_no")),
    )
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.create_index("ix_members_is_active", ["is_active"], unique=False)
        batch_op.create_index("ix_members_name", ["name"], unique=False)
        batch_op.create_index("ix_members_phone", ["phone"], unique=False)

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_kind", sa.String(length=16), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("actor_access_code_id", sa.Integer(), nullable=True),
        sa.Column("actor_display_name", sa.String(length=80), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=80), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_kind IN ('user', 'launcher', 'system')",
            name=op.f("ck_audit_logs_actor_kind_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_access_code_id"],
            ["access_codes.id"],
            name=op.f("fk_audit_logs_actor_access_code_id_access_codes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index("ix_audit_logs_actor_user_id", ["actor_user_id"], unique=False)
        batch_op.create_index("ix_audit_logs_created_at", ["created_at"], unique=False)
        batch_op.create_index(
            "ix_audit_logs_resource", ["resource_type", "resource_id"], unique=False
        )

    op.create_table(
        "course_offerings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("term_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("section_label", sa.String(length=80), nullable=True),
        sa.Column("instructor_id", sa.Integer(), nullable=True),
        sa.Column("capacity_type", sa.String(length=20), server_default="fixed", nullable=False),
        sa.Column("capacity_total", sa.Integer(), nullable=True),
        sa.Column("male_capacity", sa.Integer(), nullable=True),
        sa.Column("female_capacity", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "\n(\n  capacity_type = 'fixed'\n  AND capacity_total > 0\n  AND male_capacity IS NULL\n  AND female_capacity IS NULL\n)\nOR (\n  capacity_type = 'open'\n  AND capacity_total IS NULL\n  AND male_capacity IS NULL\n  AND female_capacity IS NULL\n)\nOR (\n  capacity_type = 'gender_split'\n  AND capacity_total IS NULL\n  AND male_capacity >= 0\n  AND female_capacity >= 0\n  AND male_capacity + female_capacity > 0\n)\n",
            name=op.f("ck_course_offerings_capacity_shape_valid"),
        ),
        sa.CheckConstraint(
            "capacity_type IN ('fixed', 'open', 'gender_split')",
            name=op.f("ck_course_offerings_capacity_type_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'open', 'closed', 'cancelled')",
            name=op.f("ck_course_offerings_status_allowed"),
        ),
        sa.CheckConstraint(
            "section_label IS NULL OR length(trim(section_label)) > 0",
            name=op.f("ck_course_offerings_section_not_blank"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_course_offerings_version_positive")),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_course_offerings_course_id_courses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["instructor_id"],
            ["instructors.id"],
            name=op.f("fk_course_offerings_instructor_id_instructors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
            name=op.f("fk_course_offerings_term_id_terms"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_offerings")),
    )
    with op.batch_alter_table("course_offerings", schema=None) as batch_op:
        batch_op.create_index("ix_course_offerings_course_id", ["course_id"], unique=False)
        batch_op.create_index("ix_course_offerings_instructor_id", ["instructor_id"], unique=False)
        batch_op.create_index(
            "ix_course_offerings_term_status", ["term_id", "status"], unique=False
        )
        batch_op.create_index(
            "uq_course_offerings_term_course_no_section",
            ["term_id", "course_id"],
            unique=True,
            sqlite_where=sa.text("section_label IS NULL"),
        )
        batch_op.create_index(
            "uq_course_offerings_term_course_section",
            ["term_id", "course_id", "section_label"],
            unique=True,
            sqlite_where=sa.text("section_label IS NOT NULL"),
        )

    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("building_floor_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(create_constraint=True, name="is_active_bool"),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_locations_version_positive")),
        sa.ForeignKeyConstraint(
            ["building_floor_id"],
            ["building_floors.id"],
            name=op.f("fk_locations_building_floor_id_building_floors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint(
            "building_floor_id", "name", name=op.f("uq_locations_building_floor_id_name")
        ),
    )
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_locations_floor_active", ["building_floor_id", "is_active"], unique=False
        )

    op.create_table(
        "operation_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_type", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="queued", nullable=False),
        sa.Column("source_name", sa.String(length=255), nullable=True),
        sa.Column("output_relative_path", sa.String(length=260), nullable=True),
        sa.Column("requested_by_user_id", sa.Integer(), nullable=True),
        sa.Column("requested_by_access_code_id", sa.Integer(), nullable=True),
        sa.Column("total_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("success_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failure_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "job_type IN ('import', 'export', 'backup', 'restore', 'notification')",
            name=op.f("ck_operation_jobs_job_type_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_operation_jobs_status_allowed"),
        ),
        sa.CheckConstraint(
            "success_count + failure_count <= total_count",
            name=op.f("ck_operation_jobs_counts_within_total"),
        ),
        sa.CheckConstraint(
            "total_count >= 0 AND success_count >= 0 AND failure_count >= 0",
            name=op.f("ck_operation_jobs_counts_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_access_code_id"],
            ["access_codes.id"],
            name=op.f("fk_operation_jobs_requested_by_access_code_id_access_codes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_operation_jobs_requested_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_jobs")),
    )
    with op.batch_alter_table("operation_jobs", schema=None) as batch_op:
        batch_op.create_index("ix_operation_jobs_type_status", ["job_type", "status"], unique=False)

    op.create_table(
        "user_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("access_code_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "expires_at > issued_at", name=op.f("ck_user_sessions_expiry_after_issue")
        ),
        sa.CheckConstraint(
            "last_seen_at >= issued_at", name=op.f("ck_user_sessions_last_seen_after_issue")
        ),
        sa.CheckConstraint(
            "revoked_at IS NULL OR revoked_at >= issued_at",
            name=op.f("ck_user_sessions_revoked_after_issue"),
        ),
        sa.ForeignKeyConstraint(
            ["access_code_id"],
            ["access_codes.id"],
            name=op.f("fk_user_sessions_access_code_id_access_codes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_sessions_token_hash")),
    )
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.create_index("ix_user_sessions_access_code_id", ["access_code_id"], unique=False)
        batch_op.create_index(
            "ix_user_sessions_lifecycle", ["expires_at", "revoked_at"], unique=False
        )
        batch_op.create_index("ix_user_sessions_user_id", ["user_id"], unique=False)

    op.create_table(
        "course_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("offering_id", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("time_slot_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "weekday BETWEEN 1 AND 7", name=op.f("ck_course_schedules_weekday_range")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_course_schedules_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["offering_id"],
            ["course_offerings.id"],
            name=op.f("fk_course_schedules_offering_id_course_offerings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["time_slot_id"],
            ["time_slots.id"],
            name=op.f("fk_course_schedules_time_slot_id_time_slots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_schedules")),
        sa.UniqueConstraint(
            "offering_id",
            "weekday",
            "time_slot_id",
            name=op.f("uq_course_schedules_offering_id_weekday_time_slot_id"),
        ),
    )
    with op.batch_alter_table("course_schedules", schema=None) as batch_op:
        batch_op.create_index("ix_course_schedules_location_id", ["location_id"], unique=False)
        batch_op.create_index("ix_course_schedules_offering_id", ["offering_id"], unique=False)
        batch_op.create_index(
            "ix_course_schedules_weekday_slot", ["weekday", "time_slot_id"], unique=False
        )

    op.create_table(
        "location_role_assignments",
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_location_role_assignments_location_id_locations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["location_roles.id"],
            name=op.f("fk_location_role_assignments_role_id_location_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "location_id", "role_id", name=op.f("pk_location_role_assignments")
        ),
    )
    with op.batch_alter_table("location_role_assignments", schema=None) as batch_op:
        batch_op.create_index("ix_location_role_assignments_role_id", ["role_id"], unique=False)

    op.create_table(
        "lottery_run_targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lottery_run_id", sa.Integer(), nullable=False),
        sa.Column("offering_id", sa.Integer(), nullable=False),
        sa.Column("capacity_type", sa.String(length=20), nullable=False),
        sa.Column("capacity_total", sa.Integer(), nullable=True),
        sa.Column("male_capacity", sa.Integer(), nullable=True),
        sa.Column("female_capacity", sa.Integer(), nullable=True),
        sa.Column("eligible_count", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "\n(\n  capacity_type = 'fixed'\n  AND capacity_total > 0\n  AND male_capacity IS NULL\n  AND female_capacity IS NULL\n)\nOR (\n  capacity_type = 'open'\n  AND capacity_total IS NULL\n  AND male_capacity IS NULL\n  AND female_capacity IS NULL\n)\nOR (\n  capacity_type = 'gender_split'\n  AND capacity_total IS NULL\n  AND male_capacity >= 0\n  AND female_capacity >= 0\n  AND male_capacity + female_capacity > 0\n)\n",
            name=op.f("ck_lottery_run_targets_capacity_shape_valid"),
        ),
        sa.CheckConstraint(
            "capacity_type IN ('fixed', 'open', 'gender_split')",
            name=op.f("ck_lottery_run_targets_capacity_type_allowed"),
        ),
        sa.CheckConstraint(
            "eligible_count >= 0", name=op.f("ck_lottery_run_targets_eligible_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["lottery_run_id"],
            ["lottery_runs.id"],
            name=op.f("fk_lottery_run_targets_lottery_run_id_lottery_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["offering_id"],
            ["course_offerings.id"],
            name=op.f("fk_lottery_run_targets_offering_id_course_offerings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lottery_run_targets")),
        sa.UniqueConstraint(
            "lottery_run_id",
            "offering_id",
            name=op.f("uq_lottery_run_targets_lottery_run_id_offering_id"),
        ),
    )
    with op.batch_alter_table("lottery_run_targets", schema=None) as batch_op:
        batch_op.create_index("ix_lottery_run_targets_offering_id", ["offering_id"], unique=False)
        batch_op.create_index("ix_lottery_run_targets_run_id", ["lottery_run_id"], unique=False)

    op.create_table(
        "operation_job_errors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=True),
        sa.Column("field_name", sa.String(length=120), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("raw_value", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "row_number IS NULL OR row_number >= 1",
            name=op.f("ck_operation_job_errors_row_number_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["operation_jobs.id"],
            name=op.f("fk_operation_job_errors_job_id_operation_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_job_errors")),
    )
    with op.batch_alter_table("operation_job_errors", schema=None) as batch_op:
        batch_op.create_index("ix_operation_job_errors_job_id", ["job_id"], unique=False)

    op.create_table(
        "registrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("offering_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="applied", nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "(status = 'cancelled' AND cancelled_at IS NOT NULL) OR (status <> 'cancelled' AND cancelled_at IS NULL)",
            name=op.f("ck_registrations_cancelled_at_matches_status"),
        ),
        sa.CheckConstraint(
            "status IN ('applied', 'selected', 'waitlisted', 'rejected', 'confirmed', 'cancelled')",
            name=op.f("ck_registrations_status_allowed"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_registrations_version_positive")),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
            name=op.f("fk_registrations_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["offering_id"],
            ["course_offerings.id"],
            name=op.f("fk_registrations_offering_id_course_offerings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registrations")),
        sa.UniqueConstraint(
            "member_id", "offering_id", name=op.f("uq_registrations_member_id_offering_id")
        ),
    )
    with op.batch_alter_table("registrations", schema=None) as batch_op:
        batch_op.create_index("ix_registrations_member_id", ["member_id"], unique=False)
        batch_op.create_index(
            "ix_registrations_offering_status", ["offering_id", "status"], unique=False
        )

    op.create_table(
        "attendance_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("offering_id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=True),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("sequence_no", sa.Integer(), server_default="1", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "sequence_no >= 1", name=op.f("ck_attendance_sessions_sequence_positive")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_attendance_sessions_version_positive")),
        sa.ForeignKeyConstraint(
            ["offering_id"],
            ["course_offerings.id"],
            name=op.f("fk_attendance_sessions_offering_id_course_offerings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["course_schedules.id"],
            name=op.f("fk_attendance_sessions_schedule_id_course_schedules"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_sessions")),
        sa.UniqueConstraint(
            "offering_id",
            "session_date",
            "sequence_no",
            name=op.f("uq_attendance_sessions_offering_id_session_date_sequence_no"),
        ),
    )
    with op.batch_alter_table("attendance_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_attendance_sessions_offering_date", ["offering_id", "session_date"], unique=False
        )

    op.create_table(
        "lottery_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lottery_run_target_id", sa.Integer(), nullable=False),
        sa.Column("registration_id", sa.Integer(), nullable=False),
        sa.Column("result", sa.String(length=16), nullable=False),
        sa.Column("result_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "result IN ('selected', 'waitlisted', 'rejected')",
            name=op.f("ck_lottery_results_result_allowed"),
        ),
        sa.CheckConstraint(
            "result_order >= 1", name=op.f("ck_lottery_results_result_order_positive")
        ),
        sa.ForeignKeyConstraint(
            ["lottery_run_target_id"],
            ["lottery_run_targets.id"],
            name=op.f("fk_lottery_results_lottery_run_target_id_lottery_run_targets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["registrations.id"],
            name=op.f("fk_lottery_results_registration_id_registrations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lottery_results")),
        sa.UniqueConstraint(
            "lottery_run_target_id",
            "registration_id",
            name=op.f("uq_lottery_results_lottery_run_target_id_registration_id"),
        ),
        sa.UniqueConstraint(
            "lottery_run_target_id",
            "result",
            "result_order",
            name=op.f("uq_lottery_results_lottery_run_target_id_result_result_order"),
        ),
    )
    with op.batch_alter_table("lottery_results", schema=None) as batch_op:
        batch_op.create_index(
            "ix_lottery_results_registration_id", ["registration_id"], unique=False
        )
        batch_op.create_index(
            "ix_lottery_results_target_id", ["lottery_run_target_id"], unique=False
        )

    op.create_table(
        "registration_status_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("registration_id", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("actor_kind", sa.String(length=16), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("actor_access_code_id", sa.Integer(), nullable=True),
        sa.Column("actor_display_name", sa.String(length=80), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_kind IN ('user', 'launcher', 'system')",
            name=op.f("ck_registration_status_history_actor_kind_allowed"),
        ),
        sa.CheckConstraint(
            "from_status IS NULL OR from_status IN ('applied', 'selected', 'waitlisted', 'rejected', 'confirmed', 'cancelled')",
            name=op.f("ck_registration_status_history_from_status_allowed"),
        ),
        sa.CheckConstraint(
            "to_status IN ('applied', 'selected', 'waitlisted', 'rejected', 'confirmed', 'cancelled')",
            name=op.f("ck_registration_status_history_to_status_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_access_code_id"],
            ["access_codes.id"],
            name=op.f("fk_registration_status_history_actor_access_code_id_access_codes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_registration_status_history_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["registrations.id"],
            name=op.f("fk_registration_status_history_registration_id_registrations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registration_status_history")),
    )
    with op.batch_alter_table("registration_status_history", schema=None) as batch_op:
        batch_op.create_index(
            "ix_registration_status_history_registration_changed",
            ["registration_id", "changed_at"],
            unique=False,
        )

    op.create_table(
        "attendance_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attendance_session_id", sa.Integer(), nullable=False),
        sa.Column("registration_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "status IN ('present', 'absent', 'late', 'excused')",
            name=op.f("ck_attendance_records_status_allowed"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_attendance_records_version_positive")),
        sa.ForeignKeyConstraint(
            ["attendance_session_id"],
            ["attendance_sessions.id"],
            name=op.f("fk_attendance_records_attendance_session_id_attendance_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["registrations.id"],
            name=op.f("fk_attendance_records_registration_id_registrations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_records")),
        sa.UniqueConstraint(
            "attendance_session_id",
            "registration_id",
            name=op.f("uq_attendance_records_attendance_session_id_registration_id"),
        ),
    )
    with op.batch_alter_table("attendance_records", schema=None) as batch_op:
        batch_op.create_index(
            "ix_attendance_records_registration_id", ["registration_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance_records", schema=None) as batch_op:
        batch_op.drop_index("ix_attendance_records_registration_id")

    op.drop_table("attendance_records")
    with op.batch_alter_table("registration_status_history", schema=None) as batch_op:
        batch_op.drop_index("ix_registration_status_history_registration_changed")

    op.drop_table("registration_status_history")
    with op.batch_alter_table("lottery_results", schema=None) as batch_op:
        batch_op.drop_index("ix_lottery_results_target_id")
        batch_op.drop_index("ix_lottery_results_registration_id")

    op.drop_table("lottery_results")
    with op.batch_alter_table("attendance_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_attendance_sessions_offering_date")

    op.drop_table("attendance_sessions")
    with op.batch_alter_table("registrations", schema=None) as batch_op:
        batch_op.drop_index("ix_registrations_offering_status")
        batch_op.drop_index("ix_registrations_member_id")

    op.drop_table("registrations")
    with op.batch_alter_table("operation_job_errors", schema=None) as batch_op:
        batch_op.drop_index("ix_operation_job_errors_job_id")

    op.drop_table("operation_job_errors")
    with op.batch_alter_table("lottery_run_targets", schema=None) as batch_op:
        batch_op.drop_index("ix_lottery_run_targets_run_id")
        batch_op.drop_index("ix_lottery_run_targets_offering_id")

    op.drop_table("lottery_run_targets")
    with op.batch_alter_table("location_role_assignments", schema=None) as batch_op:
        batch_op.drop_index("ix_location_role_assignments_role_id")

    op.drop_table("location_role_assignments")
    with op.batch_alter_table("course_schedules", schema=None) as batch_op:
        batch_op.drop_index("ix_course_schedules_weekday_slot")
        batch_op.drop_index("ix_course_schedules_offering_id")
        batch_op.drop_index("ix_course_schedules_location_id")

    op.drop_table("course_schedules")
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_user_sessions_user_id")
        batch_op.drop_index("ix_user_sessions_lifecycle")
        batch_op.drop_index("ix_user_sessions_access_code_id")

    op.drop_table("user_sessions")
    with op.batch_alter_table("operation_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_operation_jobs_type_status")

    op.drop_table("operation_jobs")
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.drop_index("ix_locations_floor_active")

    op.drop_table("locations")
    with op.batch_alter_table("course_offerings", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_course_offerings_term_course_section",
            sqlite_where=sa.text("section_label IS NOT NULL"),
        )
        batch_op.drop_index(
            "uq_course_offerings_term_course_no_section",
            sqlite_where=sa.text("section_label IS NULL"),
        )
        batch_op.drop_index("ix_course_offerings_term_status")
        batch_op.drop_index("ix_course_offerings_instructor_id")
        batch_op.drop_index("ix_course_offerings_course_id")

    op.drop_table("course_offerings")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_logs_resource")
        batch_op.drop_index("ix_audit_logs_created_at")
        batch_op.drop_index("ix_audit_logs_actor_user_id")

    op.drop_table("audit_logs")
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.drop_index("ix_members_phone")
        batch_op.drop_index("ix_members_name")
        batch_op.drop_index("ix_members_is_active")

    op.drop_table("members")
    with op.batch_alter_table("lottery_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_lottery_runs_term_status")

    op.drop_table("lottery_runs")
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.drop_index("ix_courses_category_active")

    op.drop_table("courses")
    with op.batch_alter_table("building_floors", schema=None) as batch_op:
        batch_op.drop_index("ix_building_floors_building_id")

    op.drop_table("building_floors")
    with op.batch_alter_table("access_codes", schema=None) as batch_op:
        batch_op.drop_index("ix_access_codes_user_id")
        batch_op.drop_index("ix_access_codes_lifecycle")

    op.drop_table("access_codes")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("ix_users_role_is_active")

    op.drop_table("users")
    op.drop_table("time_slots")
    op.drop_table("terms")
    op.drop_table("organization_settings")
    with op.batch_alter_table("operation_locks", schema=None) as batch_op:
        batch_op.drop_index("ix_operation_locks_expires_at")

    op.drop_table("operation_locks")
    op.drop_table("location_roles")
    op.drop_table("instructors")
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.drop_index("ix_idempotency_records_expires_at")

    op.drop_table("idempotency_records")
    op.drop_table("gender_codes")
    op.drop_table("course_categories")
    op.drop_table("buildings")
    # ### end Alembic commands ###
